import { useEffect, useRef, useState } from 'react';
import { Bot, Mic, Send, X, Volume2, ExternalLink, Square, PauseCircle, Radio } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { api } from '../services/api';
import { useProfile } from '../context/ProfileContext';
import { useLanguage } from '../context/LanguageContext';

const voiceLocales=['en-IN','hi-IN','bn-IN','mr-IN','ta-IN','te-IN','gu-IN','kn-IN','ml-IN','pa-IN'];
function pickVoice(lang){const voices=window.speechSynthesis?.getVoices?.()||[]; return voices.find(v=>v.lang?.toLowerCase()===lang.toLowerCase())||voices.find(v=>v.lang?.toLowerCase().startsWith(lang.split('-')[0].toLowerCase()))||voices[0]||null;}

export default function FloatingAI(){
 const {profile,updateProfile}=useProfile(); const {language,t,changeLanguage,options}=useLanguage(); const navigate=useNavigate();
 const [open,setOpen]=useState(false); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false); const [listening,setListening]=useState(false); const [interim,setInterim]=useState(''); const [speaking,setSpeaking]=useState(false); const recognitionRef=useRef(null);
 const [messages,setMessages]=useState([{role:'assistant',content:t('aiIntro')}]);
 useEffect(()=>{if(messages.length===1)setMessages([{role:'assistant',content:t('aiIntro')}])},[language]);
 const sttLang=language==='hinglish'?'hi-IN':(language==='en-IN'?'en-IN':(language==='auto'?'en-IN':language));
 const stopSpeaking=()=>{window.speechSynthesis?.cancel();setSpeaking(false)};
 const speak=(text)=>{if(!('speechSynthesis' in window))return;stopSpeaking();const chunks=String(text).match(/[^.!?\n]{1,180}[.!?\n]?/g)||[String(text)];let i=0;const next=()=>{if(i>=chunks.length){setSpeaking(false);return}const u=new SpeechSynthesisUtterance(chunks[i++]);u.lang=sttLang;const v=pickVoice(sttLang);if(v)u.voice=v;u.rate=.96;u.pitch=1;u.onend=next;u.onerror=()=>setSpeaking(false);setSpeaking(true);window.speechSynthesis.speak(u)};next()};
 const stopVoice=()=>{recognitionRef.current?.stop();setListening(false);setInterim('')};
 const startVoice=()=>{if(listening){stopVoice();return}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setMessage(t('voiceUnsupported'));return}const r=new SR();recognitionRef.current=r;r.lang=sttLang;r.interimResults=true;r.continuous=false;r.maxAlternatives=3;setListening(true);setInterim('');r.onresult=e=>{let finalText='';let live='';for(let i=e.resultIndex;i<e.results.length;i++){const tx=e.results[i][0].transcript;if(e.results[i].isFinal)finalText+=tx;else live+=tx}if(live)setInterim(live);if(finalText){setMessage(prev=>(prev?prev+' ':'')+finalText);setInterim('')}};r.onerror=e=>{setListening(false);setInterim('');setMessage(prev=>prev|| (e.error==='not-allowed'?t('micDenied'):t('voiceStopped')))};r.onend=()=>{setListening(false);setInterim('')};try{r.start()}catch{setListening(false)}};
 const send=async()=>{if(!message.trim()||busy)return;const user=message.trim();const safeHistory=messages.map(({role,content})=>({role,content})).slice(-10);setMessages(m=>[...m,{role:'user',content:user}]);setMessage('');setBusy(true);try{const res=await api.copilot({message:user,profile,history:safeHistory,language});if(res.profile_patch&&Object.keys(res.profile_patch).length)updateProfile(res.profile_patch);setMessages(m=>[...m,{role:'assistant',content:res.answer,actions:res.actions||[],retrieved:res.retrieved||[],mode:res.mode}]);}catch(e){setMessages(m=>[...m,{role:'assistant',content:`I couldn't complete that request. ${e.message||'Please check the local AI service.'}`}]);}finally{setBusy(false)}};
 const localeOptions=options.filter(o=>o.code==='en-IN'||o.code==='hi-IN'||o.code==='hinglish'||voiceLocales.includes(o.code));
 return <>{!open&&<button className="ai-fab" onClick={()=>setOpen(true)} aria-label="Open AI Copilot"><Bot size={24}/><span>{t('ai')}</span><Radio size={12}/></button>}
 {open&&<div className="copilot-panel"><div className="copilot-head"><div className="copilot-title"><div className="copilot-avatar"><Bot size={18}/></div><div><strong>Scheme Setu AI</strong><small>RAG • profile • tools • voice</small></div></div><button className="icon-btn" onClick={()=>{stopSpeaking();setOpen(false)}}><X size={18}/></button></div>
 <div className="copilot-messages">{messages.map((m,i)=><div className={`chat-bubble ${m.role}`} key={i}><div>{m.content}</div>{m.role==='assistant'&&<div className="chat-actions">{m.actions?.map(a=><button key={`${a.target}-${a.label}`} className="chip-btn" onClick={()=>navigate(a.target)}><ExternalLink size={13}/>{a.label}</button>)}<button className="icon-chip" onClick={()=>speak(m.content)} title={t('listen')}><Volume2 size={13}/>{t('listen')}</button><button className="icon-chip" onClick={stopSpeaking} title={t('stop')}><Square size={11}/></button></div>}</div>)}{interim&&<div className="voice-live"><span className="live-dot"></span>{interim}</div>}{busy&&<div className="typing">Thinking…</div>}</div>
 <div className="copilot-input"><div className="copilot-tools"><select value={language} onChange={e=>changeLanguage(e.target.value)} aria-label={t('language')}>{localeOptions.map(o=><option key={o.code} value={o.code}>{o.label}</option>)}</select></div><textarea value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder={t('askPlaceholder')} rows={2}/><div className="input-actions"><button className={`voice-btn ${listening?'recording':''}`} onClick={startVoice}><Mic size={18}/>{listening?t('listening'):t('voice')}</button><div className="input-right">{speaking&&<button className="icon-btn voice-state" onClick={()=>window.speechSynthesis.pause()} title={t('pause')}><PauseCircle size={17}/></button>}<button className="send-btn" onClick={send}><Send size={17}/>{t('send')}</button></div></div></div></div>}</>
}
