import { Link } from 'react-router-dom';
import { ArrowRight, Bot, Calculator, FileCheck2, MapPinned, ShieldCheck, Sparkles, Users, WalletCards, Bell, Route } from 'lucide-react';
import hero from '../assets/home_hero.webp'; import auto from '../assets/home_auto.webp'; import tailoring from '../assets/home_tailoring.webp'; import artisan from '../assets/home_pottery.webp'; import shop from '../assets/home_kirana.webp'; import digital from '../assets/dashboard_digital.webp'; import food from '../assets/home_food.webp'; import logo from '../assets/scheme_setu_logo_square.png';
import { useLanguage } from '../context/LanguageContext';
export default function Home(){const {t}=useLanguage();return <div className="home-page page-wrap">
<section className="hero-card patriotic-hero"><img className="hero-bg" src={hero} alt="Indian entrepreneurs building a local food enterprise"/><div className="hero-overlay"/><div className="hero-copy"><div className="eyebrow hero-eyebrow">BHARAT × FINTECH × AI</div><h1>From a local idea to a confident finance journey.</h1><p>Scheme Setu AI connects scheme discovery, eligibility, finance planning, documents, partner routing and a multilingual AI Copilot in one responsive experience.</p><div className="hero-actions"><Link className="btn btn-primary" to="/dashboard">{t('start')} <ArrowRight size={17}/></Link><Link className="btn btn-ghost hero-light-btn" to="/schemes">{t('explore')}</Link></div><div className="hero-trust"><span><ShieldCheck size={16}/> Source-aware</span><span><Sparkles size={16}/> RAG-powered</span><span><Users size={16}/> Bharat-first</span></div></div><div className="hero-visual"><div className="hero-logo-lockup"><img src={logo} alt="Scheme Setu AI logo"/><div><strong>Scheme Setu AI</strong><small>Bharat-first finance bridge</small></div></div><div className="image-badge"><div className="badge-icon"><Bot size={19}/></div><div><strong>{t('ai')}</strong><small>Text • voice • multilingual</small></div></div></div></section>
<section className="brand-banner"><div className="brand-banner-logo"><img src={logo} alt="Scheme Setu AI"/></div><div><span className="section-kicker">A DIFFERENT KIND OF GOVERNMENT UX</span><h2>Built around the user journey, not around a pile of PDFs.</h2><p>Discover → Understand → Calculate → Prepare → Route → Track.</p></div></section>
<section className="journey-section"><div className="section-kicker">ONE JOURNEY</div><h2>Talk. Match. Plan. Move.</h2><div className="journey-grid"><div className="journey-card"><Bot/><span>01</span><h3>Tell your story</h3><p>Describe your age, category, business idea and funding need in your own words.</p><img src={tailoring} alt="Women tailoring together"/></div><div className="journey-card"><Sparkles/><span>02</span><h3>Get matched</h3><p>Eligibility rules + ranking turn a profile into a focused shortlist.</p><img src={digital} alt="Young entrepreneurs collaborating"/></div><div className="journey-card"><WalletCards/><span>03</span><h3>Make the numbers real</h3><p>Compare loan scenarios, subsidy impact and repayment before you apply.</p><img src={shop} alt="Small retail enterprise"/></div><div className="journey-card"><MapPinned/><span>04</span><h3>Reach the right door</h3><p>Find a relevant nearby partner and route there from one screen.</p><img src={auto} alt="Auto-rickshaw entrepreneur"/></div></div></section>
<section className="image-story-grid"><div className="story-image big"><img src={food} alt="Indian food enterprise"/><div><span>FOOD • MICRO-ENTERPRISE</span><strong>Local products can become confident businesses.</strong></div></div><div className="story-copy panel"><div className="section-kicker">TRUST LAYER</div><h2>Why a scheme, not just a list?</h2><p>Every recommendation can surface the eligibility signals, financial terms, document checklist and evidence trail so users understand the next move.</p><Link className="text-link" to="/schemes">Explore scheme intelligence →</Link></div><div className="story-image"><img src={artisan} alt="Indian artisan at work"/><div><span>CRAFT • ENTREPRENEURSHIP</span><strong>Traditional skills can become modern enterprises.</strong></div></div></section>
<section className="feature-strip"><div className="feature-copy"><div className="section-kicker">BUILT FOR ACTION</div><h2>Not another scheme directory.</h2><p>From eligibility gap detection to reminders and roadmaps, Scheme Setu is designed around decisions.</p><div className="pill-row"><span><Calculator size={14}/> Finance</span><span><FileCheck2 size={14}/> Documents</span><span><Bell size={14}/> Alerts</span><span><Route size={14}/> Roadmap</span></div><Link to="/dashboard" className="text-link">Open the dashboard →</Link></div><div className="mini-grid"><div><Calculator/><strong>Financial intelligence</strong><span>EMI • scenarios • charts</span></div><div><FileCheck2/><strong>Eligibility gap detector</strong><span>Know what to fix</span></div><div><MapPinned/><strong>Smart partner routing</strong><span>Optional scheme filter • 300 km</span></div><div><Bot/><strong>AI Copilot</strong><span>RAG • tools • voice</span></div></div></section>
</div>}
