import { useState } from 'react';
import { Save, UserRound, Sparkles } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import PageVisual from '../components/PageVisual';
import { useProfile } from '../context/ProfileContext';
import { useNavigate } from 'react-router-dom';
import { useLanguage } from '../context/LanguageContext';

export default function Profile(){const {profile,updateProfile}=useProfile();const {t}=useLanguage();const [form,setForm]=useState(profile);const nav=useNavigate();const on=(k,v)=>setForm(f=>({...f,[k]:v}));const save=()=>{updateProfile({...form,age:form.age?Number(form.age):'',loan_amount:form.loan_amount?Number(form.loan_amount):0,income:form.income?Number(form.income):0});nav('/dashboard')};return <div className="page-wrap"><PageVisual kind="profile" label="PEOPLE • PROFILE">{t('profile')}</PageVisual><PageHeader eyebrow="PERSONAL PROFILE" title="Make your profile work for you." subtitle="The copilot uses these signals for matching, gap detection and actions."/><section className="panel profile-form"><div className="profile-form-head"><div className="big-avatar"><UserRound/></div><div><strong>My Scheme Setu profile</strong><span>Saved locally in this browser for the prototype.</span></div></div><div className="profile-ai-tip"><Sparkles size={16}/><span>Tip: you can also tell the AI your details in one sentence and it will patch this profile automatically.</span></div><div className="input-grid three"><label>Name<input value={form.name} onChange={e=>on('name',e.target.value)}/></label><label>Age<input type="number" value={form.age} onChange={e=>on('age',e.target.value)}/></label><label>Gender<select value={form.gender} onChange={e=>on('gender',e.target.value)}><option value="">Select</option><option>Female</option><option>Male</option><option>Other</option></select></label><label>Category<select value={form.category} onChange={e=>on('category',e.target.value)}><option value="">Select</option><option>SC</option><option>ST</option><option>OBC</option><option>General</option></select></label><label>State<input value={form.state} onChange={e=>on('state',e.target.value)}/></label><label>District<input value={form.district} onChange={e=>on('district',e.target.value)}/></label><label>Business type<input value={form.business_type} onChange={e=>on('business_type',e.target.value)}/></label><label>Loan amount<input type="number" value={form.loan_amount} onChange={e=>on('loan_amount',e.target.value)}/></label><label>Annual income<input type="number" value={form.income} onChange={e=>on('income',e.target.value)}/></label></div><button className="btn btn-primary" onClick={save}><Save size={17}/> {t('save')} {t('profile')}</button></section></div>}
