import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, ChevronRight, Circle, Route, ShieldCheck } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import PageHeader from '../components/PageHeader';
import PageVisual from '../components/PageVisual';
import { api } from '../services/api';
import { useLanguage } from '../context/LanguageContext';

export default function Roadmap(){const {id}=useParams();const nav=useNavigate();const {t}=useLanguage();const [schemes,setSchemes]=useState([]);const [selected,setSelected]=useState(id||'');const [r,setR]=useState(null);const [done,setDone]=useState(()=>{try{return JSON.parse(localStorage.getItem('schemeSetuRoadmapProgress')||'{}')}catch{return {}}});useEffect(()=>{api.schemes().then(x=>setSchemes(x.items||[])).catch(()=>{});},[]);useEffect(()=>{if(selected)api.roadmap(selected).then(setR).catch(()=>{});else setR(null)},[selected]);useEffect(()=>{if(id&&selected!==id)setSelected(id)},[id]);const selectedScheme=useMemo(()=>schemes.find(s=>s.scheme_id===selected),[schemes,selected]);const toggle=(step)=>{const key=`${selected}:${step}`;const next={...done,[key]:!done[key]};setDone(next);localStorage.setItem('schemeSetuRoadmapProgress',JSON.stringify(next))}; const nextStep=(steps)=>{const n=steps.find(x=>!done[`${selected}:${x.step}`]); if(n){toggle(n.step); const el=document.querySelector(`[data-roadstep="${n.step}"]`); el?.scrollIntoView({behavior:'smooth',block:'center'});}};if(!selected)return <div className="page-wrap"><PageVisual kind="roadmap" label="WOMEN • JOURNEY">{t('roadmap')}</PageVisual><PageHeader eyebrow="APPLICATION ROADMAP" title="One roadmap, one scheme at a time." subtitle="Choose a scheme to turn it into an interactive next-step plan."/><section className="roadmap-selector panel"><Route size={23}/><div><label>Select scheme</label><select value={selected} onChange={e=>{setSelected(e.target.value); if(e.target.value)nav(`/roadmap/${e.target.value}`)}}><option value="">Choose a scheme…</option>{schemes.map(s=><option value={s.scheme_id} key={s.scheme_id}>{s.scheme_name}</option>)}</select></div><Link className="btn btn-light" to="/schemes">Browse schemes</Link></section><div className="roadmap-feature panel"><ShieldCheck size={24}/><div><strong>Roadmap stays useful even before live application tracking.</strong><p>The prototype remembers your completed steps in this browser. Live status will plug in when authorized institutional APIs are available.</p></div></div></div>;
 return <div className="page-wrap"><PageVisual kind="roadmap" label="WOMEN • JOURNEY">{t('roadmap')}</PageVisual><PageHeader eyebrow="APPLICATION ROADMAP" title={r?.scheme||selectedScheme?.scheme_name||'Application roadmap'} subtitle="A live, interactive checklist. Your progress stays in this browser." action={<button className="btn btn-light" onClick={()=>{setSelected('');nav('/roadmap')}}>Change scheme</button>}/>{r?.steps&&<div className="timeline">{r.steps.map((s,i)=>{const isDone=!!done[`${selected}:${s.step}`];return <div className="timeline-item" key={s.step}><div className={`timeline-num ${isDone?'done':''}`}>{isDone?<CheckCircle2 size={18}/>:String(i+1).padStart(2,'0')}</div><div className="timeline-line"/><div className="timeline-card interactive-step" data-roadstep={s.step}><span>STEP {s.step}</span><h2>{s.title}</h2><p>{s.detail}</p><div className="step-actions"><button className={`step-check-btn ${isDone?'done':''}`} onClick={()=>toggle(s.step)}>{isDone?<CheckCircle2 size={16}/>:<Circle size={16}/>} {isDone?t('completed'):t('markDone')}</button>{i<r.steps.length-1&&<button className="step-next" onClick={()=>nextStep(r.steps)}>{t('ready')} <ChevronRight size={15}/></button>}</div></div></div>})}</div>}</div>}
