import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowUpRight, CheckCircle2, FileText, IndianRupee, MapPinned } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import PageHeader from '../components/PageHeader';
import PageVisual from '../components/PageVisual';
import { api } from '../services/api';
import WhyThisScheme from '../components/WhyThisScheme';
import EligibilityGapPanel from '../components/EligibilityGapPanel';

export default function SchemeDetails(){const {id}=useParams();const [s,setS]=useState(null);const [road,setRoad]=useState(null);const nav=useNavigate();useEffect(()=>{api.scheme(id).then(setS).catch(()=>{});api.roadmap(id).then(setRoad).catch(()=>{});},[id]);if(!s)return <div className="page-wrap"><div className="empty-state">Loading scheme…</div></div>;
return <div className="page-wrap"><button className="back-btn" onClick={()=>nav(-1)}><ArrowLeft size={16}/> Back</button><PageVisual kind="details" label="SCHEME • EVIDENCE">{s.scheme_name}</PageVisual><PageHeader eyebrow={s.scheme_type||'SCHEME'} title={s.scheme_name} subtitle={s.description}/><div className="detail-grid"><section className="panel"><div className="metric-row"><div><span>Maximum loan</span><strong>₹{Number(s.max_loan_inr).toLocaleString('en-IN')}</strong></div><div><span>Subsidy</span><strong>{s.max_subsidy_pct}%</strong></div><div><span>Tenure</span><strong>{s.tenure_years} yrs</strong></div><div><span>Interest</span><strong>{s.interest_rate}</strong></div></div><div className="detail-section"><h3>Eligibility signals</h3><div className="tag-cloud"><span>{s.category}</span><span>{s.gender}</span><span>{s.business_type}</span><span>{s.state}</span><span>{s.min_age}-{s.max_age} yrs</span></div></div><WhyThisScheme scheme={s} full/><EligibilityGapPanel schemeId={s.scheme_id}/><div className="detail-section"><h3><FileText size={17}/> Documents</h3><div className="check-list">{String(s.documents).split(';').filter(Boolean).map(x=><div key={x}><CheckCircle2 size={16}/>{x}</div>)}</div></div><div className="detail-actions"><a className="btn btn-primary" href={s.apply_link} target="_blank" rel="noreferrer">Open official source <ArrowUpRight size={16}/></a><Link className="btn btn-light" to={`/roadmap/${s.scheme_id}`}>Application roadmap</Link></div></section><aside className="panel sticky-panel"><div className="section-kicker">HOW SCHEME SETU HELPS</div><h2>One decision at a time.</h2><div className="step-mini"><MapPinned/><div><strong>Find a partner</strong><span>Route from the partner locator.</span></div></div><div className="step-mini"><IndianRupee/><div><strong>Model your loan</strong><span>See an indicative repayment.</span></div></div><div className="step-mini"><FileText/><div><strong>Prepare documents</strong><span>Follow an interactive roadmap.</span></div></div>{road?.steps?.length&&<Link className="text-link" to={`/roadmap/${s.scheme_id}`}>See roadmap →</Link>}</aside></div></div>}
