import { useEffect, useMemo, useState } from 'react';
import { Search, SlidersHorizontal, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import PageHeader from '../components/PageHeader';
import PageVisual from '../components/PageVisual';
import SchemeCard from '../components/SchemeCard';
import { api } from '../services/api';
import { useProfile } from '../context/ProfileContext';
import { useLanguage } from '../context/LanguageContext';

export default function Schemes(){const {profile}=useProfile();const {t}=useLanguage();const [items,setItems]=useState([]);const [q,setQ]=useState('');const [category,setCategory]=useState('');const [loading,setLoading]=useState(true);const [matched,setMatched]=useState([]);useEffect(()=>{api.schemes().then(r=>setItems(r.items)).catch(()=>{}).finally(()=>setLoading(false));if(profile.age)api.match(profile).then(r=>setMatched(r.items)).catch(()=>{})},[JSON.stringify(profile)]);const visible=useMemo(()=>items.filter(s=>!q||`${s.scheme_name} ${s.description} ${s.business_type}`.toLowerCase().includes(q.toLowerCase())).filter(s=>!category||String(s.category).toLowerCase().includes(category.toLowerCase())),[items,q,category]);return <div className="page-wrap"><PageVisual kind="schemes" label="WOMEN • MICRO-ENTERPRISE">{t('schemes')}</PageVisual><PageHeader eyebrow="DISCOVER" title={t('schemes')} subtitle="Browse the seed knowledge base now; verified government data can replace it without changing the UI." action={<Link className="btn btn-light" to="/compare">{t('compare')}</Link>}/><div className="search-row"><div className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search scheme, business type, benefit…"/></div><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option><option>SC</option><option>ST</option><option>Women</option><option>OBC</option><option>General</option></select><button className="btn btn-light"><SlidersHorizontal size={16}/> Filters</button></div>{matched.length>0&&<div className="match-banner"><Sparkles size={18}/><div><strong>{matched.filter(x=>x.eligible).length} personalized matches</strong><span>Based on your saved profile.</span></div><Link className="text-link" to="/dashboard">Dashboard →</Link></div>}{loading?<div className="empty-state">Loading schemes…</div>:<div className="scheme-grid wide">{visible.map(s=><SchemeCard scheme={s} key={s.scheme_id}/>)}</div>}</div>}
